spring.application.name=backend
spring.datasource.url=jdbc:h2:mem:test
server.servlet.context-path=/api
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
server.servlet.session.cookie.path=/api
server.servlet.session.timeout=24h


logging.level.org.springframework.web=OFF
logging.level.org.springframework.web.servlet=OFF
logging.level.org.springframework.web.servlet.mvc.method.annotation=OFF
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
