type Query {

    me: User
    projects: [Project!]!
    teams: [Team!]!
    users: [User!]!
    skills: [Skill!]!
}

interface Node {
    id: ID!
}

type Project implements Node {
    id: ID!
    name: String!
    teams: [Team!]!
    status: ProjectStatus!
}

type Skill implements Node { #ongoing
    id: ID!
    name: String!
}
type Team implements Node {
    id: ID!
    name: String!
    users: [User!]!
}
type User implements Node {
    id: ID!
    name: String!
    email: String!
    projects: [Project!]!
    teams: [Team!]!
    skills: [Skill!]!
}

enum ProjectStatus {
    IN_PROGRESS
    COMPLETED
}
