type Query {
    me: User

    projects: [Project!]!
    teams: [Team!]!
    users: [User!]!
    skills: [Skill!]!

    user(userId: ID!): User!
    project(projectId: ID!): Project!


}

interface Node {
    id: ID!
}

type Project implements Node {
    id: ID!
    name: String!
    teams: [Team!]!
    status: String
    recommendedUsers: [ProjectUserMatch!]!
}

type Skill implements Node {
    id: ID!
    name: String!
}
type Team implements Node {
    id: ID!
    name: String!
    users: [User!]!
}
type User implements Node {
    id: ID!
    name: String!
    email: String!
    projects: [Project!]!
    teams: [Team!]!
    skills: [Skill!]!
    recommendedProjects: [UserProjectMatch!]!
}


type ProjectUserMatch {
    user_id: Int
    user_name: String
    role_configuration_id: Int
    matched_skills: Int
    match_percentage: Float
    role_name: String
}

type UserProjectMatch {
    project_id: Int
    project_name: String
    role_configuration_id: Int
    matched_skills: Int
    match_percentage: Float
    role_name: String
}

type ProjectConfiguration {
    id: ID!
}




type Mutation {
    createTeam(name: String!): Team
    createProject(name: String!): Project
}







